# File: mkdocs.yml

site_name: IITT HPC Documentation
site_url: https://example.com/
site_description: ""
site_author: P Vamshi Seshasayan <vamshi@iittp.ac.in>
nav:
    - Home: index.md    
    - Lotus Cluster: lotus/index.md
    - Orchid Cluster: orchid/index.md
    - Using the HPC Systems:       
      - Requesting an account: hpc/requesting-an-account.md
      - Connecting to the clusters: hpc/connecting-to-clusters.md
      - Using software with modules: hpc/using-modules.md
      - Storage: hpc/storage.md
      - Transferring files: hpc/transferring-files.md
      - Job script examples: hpc/pbsscript-examples.md
      - Running Jobs with PBS: hpc/running-jobs.md
      - Monitoring Jobs: hpc/monitoring-jobs.md
      - Debugging: hpc/debugging.md
    - Using Ansys on Lotus Cluster: ''
    - Do's and Don'ts: hpc/dos-and-donts.md
    - Getting Help: hpc/getting-help.md
    - Useful Resources: hpc/resources.md

theme:
    name: material
    custom_dir: overrides
    palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    font:
      text: Nunito
    features:      
      - navigation.expand
      - navigation.top
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    icon:
      repo: fontawesome/brands/github


repo_url: https://github.com/P-Vamshi-Seshasayan/iitt-hpc-docs
repo_name: 'iitt-hpc-docs'

markdown_extensions:  
  - attr_list
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
      remove_comments: true
  - git-revision-date

copyright: Copyright &copy; 2021 Computer Center, IIT Tirupati


